package com.example.stagger.demo;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Demo order APIs generated by Stagger.
 */
@RestController
@RequestMapping("/api/orders")
public class OrderController {

    /**
     * Query one order by ID.
     *
     * @param id order ID
     * @return order detail payload
     */
    @GetMapping("/{id}")
    public OrderView getById(@PathVariable("id") Long id) {
        OrderView view = new OrderView();
        view.setId(id);
        view.setStatus("PAID");
        view.setAmount(99_00L);
        return view;
    }

    /**
     * Create a new order.
     *
     * @param request creation payload
     * @return created order
     */
    @PostMapping
    public OrderView create(@RequestBody CreateOrderRequest request) {
        OrderView view = new OrderView();
        view.setId(1001L);
        view.setStatus("CREATED");
        view.setAmount(request.getAmount());
        return view;
    }
}
