uuid-string=${mock.uuid}
traceid-string=${mock.uuid}
id-string=${mock.int.1.200}
ids-string=${mock.int.1.200}
nickname-string=${mock.username}
hostname-string=${mock.ipv4}
name-string=${mock.username}
author-string=${mock.author}
url-string=${mock.url}
username-string=${mock.username}
code-int=0
index-int=1
index-integer=1
page-int=1
page-integer=1
age-int=${mock.int.0.70}
age-integer=${mock.int.0.70}
email-string=${mock.email}
domain-string=${mock.domain}
phone-string=${mock.phone}
mobile-string=${mock.phone}
telephone-string=${mock.telephone}
address-string=${mock.address}
ip-string=${mock.ipv4}
ipv4-string=${mock.ipv4}
ipv6-string=${mock.ipv6}
company-string=${mock.company}
timestamp-long=${mock.now.millis}
timestamp-string=${mock.now.datetime}
time-long=${mock.now.millis}
time-string=${mock.now.datetime}
birthday-string=${mock.now.date}
birthday-long=${mock.now.millis}
code-string=${mock.int.100.99999}
message-string=${mock.message}
date-string=${mock.now.date}
date-date=${mock.now.date}
begintime-date=${mock.now.datetime}
endtime-date=${mock.now.datetime}
time-localtime=${mock.now.time}
state-int=${mock.int.0.10}
state-integer=${mock.int.0.10}
flag-int=${mock.int.0.10}
flag-integer=${mock.int.0.10}
flag-boolean=true
flag-Boolean=false
idcard-string=${mock.idcard}
sex-int=${mock.int.0.2}
sex-integer=${mock.int.0.2}
gender-int=${mock.int.0.2}
gender-integer=${mock.int.0.2}
limit-int=10
limit-integer=10
size-int=10
size-integer=10
offset-int=1
offset-integer=1
offset-long=1
version-string=${mock.semver}
