name: Release Publish (Central)

on:
  release:
    types: [created]

jobs:
  publish:
    if: ${{ github.repository == 'HsinDumas/stagger' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Plugin Repository
        uses: actions/checkout@v5

      - name: Set Up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: gradle

      - name: Publish and release artifacts to Maven Central
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_IN_MEMORY_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}
        run: |
          ./gradlew --no-daemon publishReleaseToMavenCentral
