name: Release Publish (Gradle)

on:
  release:
    types: [created]

jobs:
  publish:
    if: ${{ github.repository == 'HsinDumas/stagger' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Plugin Repository
        uses: actions/checkout@v5

      - name: Set Up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: gradle

      - name: Publish artifacts to Maven Local
        run: |
          ./gradlew --no-daemon \
            :stagger-core:publishToMavenLocal \
            :stagger-maven-plugin:publishToMavenLocal \
            :stagger-gradle-plugin:publishToMavenLocal
